config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: redirect('/orders')

  get    'login',  to: 'sessions#new', as: 'login'
  post   'login',  to: 'sessions#create'
  get    'logout', to: 'sessions#destroy', as: 'logout'
  delete 'logout', to: 'sessions#destroy'

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :orders, only: :create
    end
    namespace :v2 do
      resources :orders, only: :create
    end
    namespace :v3 do
      resources :orders, only: :create
    end
    namespace :v4 do
      resources :orders, only: :create
    end
  end

  scope :autocomplete, as: :autocomplete do
    get :customers, to: 'autocomplete#customers'
    get :drives, to: 'autocomplete#drives'
  end

  resources :csv_files, path: 'csv', only: %i[create index show]

  get 'help', to: 'help#index', as: 'helps'
  get 'help/*page', to: 'help#show', as: 'help'

  resources :orders, except: [:destroy] do
    collection do
      get 'mine', as: 'my'
    end
    resource :day_count, defaults: { format: 'json' }, only: :show
    resource :state, only: :create
    resources :users, only: %i[create destroy]
  end

  resources :passwords, except: :delete

  resources :reports do
    collection do
      post :preview
    end

    member do
      get :run
    end
  end

  resources :users, except: :destroy do
    resource :roles, only: %i[edit update]
    member do
      patch :disable
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_and_belongs_to_many :orders
  has_and_belongs_to_many :roles
  has_many :drive_events, dependent: :restrict_with_exception
  has_many :order_states, dependent: :restrict_with_exception

  attr_accessor :remember_me

  validates :name,
            presence: true,
            length: { maximum: 255 }
  validates :email,
            presence: true,
            uniqueness: true,
            length: { maximum: 255 },
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :password,
            presence: true,
            confirmation: { if: -> { persisted? } },
            if: -> { new_record? || password.present? }

  # scopes
  scope :exclude_users, ->(users) { where.not(id: users) if users.present? && !users.empty? }
  scope :by_name, -> { order(name: :asc) }
  scope :including_roles, -> { references(:users_roles).includes(:roles, roles_users: :role) }

  def self.all_by_name(*except_users)
    exclude_users(except_users).by_name
  end

  def role?(*keys)
    !roles.where(key: keys).empty?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: %i[edit show update disable]

  # POST /users or POST /order/:order_id/users
  def create
    if params[:order_id]
      @order = Order.find params[:order_id]
      authorize(@order, :update?)

      @user = User.find(params.require(:user).require(:id))
      @order.add_user_to_watchlist @user
      redirect_to @order, notice: "#{@user.name} added to watchlist"
    else
      @user = User.new(permitted_attributes(User.new))
      authorize @user
      @user.password = SecureRandom.hex

      if @user.save
        UserMailer.new_user_email(@user).deliver_later
        notice = 'User was successfully created.'
        if policy(Contexts::UserRole.new(@user)).edit?
          notice = [notice, 'New users have no roles and cannot perform many '\
                            'actions on the site. Make sure you grant this '\
                            'user some roles before they use the site']
        end
        redirect_to user_path(@user), notice: notice
      else
        flash.now[:error] = 'User could not be created'
        render :new, status: :unprocessable_entity
      end
    end
  end

  # DELETE /order/:order_id/users/:id
  def destroy
    @order = Order.find params[:order_id]
    authorize(@order, :update?)

    @user = @order.users.find(params[:id])
    @order.user_ids -= [@user.id]
    redirect_to @order
  end

  # GET /users/:id/edit
  def edit
    authorize @user
  end

  # GET /users
  def index
    @users = User.including_roles.by_name
    authorize @users
    @user = User.new
    authorize @user, :new?
  end

  # GET /users/new
  def new
    @user = User.new
    authorize @user
  end

  # GET /users/:id
  def show
    authorize @user
  end

  # PATCH/PUT /users/:id
  def update
    authorize @user
    attrs = permitted_attributes(@user).reject { |_k, v| v.blank? }
    @user.name = attrs[:name] if attrs.key? :name
    @user.email = attrs[:email] if attrs.key? :email
    if attrs.key? :password
      @user.password = attrs[:password]
      @user.password_confirmation = attrs.fetch(:password_confirmation, '')
    end

    if @user.save
      redirect_to user_path(@user), notice: 'Profile updated successfully'
    else
      flash.now[:error] = 'Profile could not be updated'
      render :edit, status: :unprocessable_entity
    end
  end

  def disable
    authorize @user
    if params[:user][:disabled_at] == '1'
      if @user.disabled_at.nil?
        @user.disabled_at = Time.now
        @user.disabled_reason = params[:user][:disabled_reason]
      else
        @user.disabled_at = nil
        @user.disabled_reason = nil
      end
      @user.save
    end
    redirect_to user_path(@user)
  end

  private

  def find_user
    @user = User.including_roles.find(params[:id])
  end
end

app/views/users/_form.html.haml
= simple_form_for @user, url: (@user.new_record? ? users_path : user_path(@user)) do |f|
  = f.input :name
  = f.input :email
  - if not @user.new_record? and policy(@user).update?
    = f.input :password
    = f.input :password_confirmation

  %button.btn.btn-primary{type: 'submit', data: {disable_with: 'Saving...'}}= fa_icon 'check', text: 'Save All'
  - if modal
    %button.btn.btn-secondary{type: 'button', data: {dismiss: 'modal'}}= fa_icon 'ban', text: 'Cancel'
  - else
    %a.btn.btn-secondary{href: (@user.new_record? ? users_path : user_path(@user))}= fa_icon 'ban', text: 'Cancel'

app/views/users/_modal_form.html.haml
.modal.fade{id: dom_id(@user, "#{action}-modal"), aria_labelledby: '#modal-form-label', role: "dialog", tabindex: "-1"}
  .modal-dialog{role: "document"}
    .modal-content
      .modal-header
        %button.close{type: "button", data: {dismiss: "modal"}, aria_label: "Close"}
          %span{aria_hidden: "true"}
            %i.fa.fa-fw.fa-times
          %span.sr-only Close
        %h4#modal-form-label.modal-title
          = action.titleize
          user
      .modal-body= render 'form', modal: true

app/views/users/create.html.haml
%h1 Users#create
%p Find me in app/views/users/create.html.haml

app/views/users/edit.html.haml
- content_for :title, "Editing user: #{@user.name}"
- content_for :heading, 'Edit User'
- content_for :subheading, @user.name
- content_for :breadcrumbs do
  %li.breadcrumb-item
    %a{href: users_path}= fa_icon 'group', text: 'Users'
  %li.breadcrumb-item
    %a{href: user_path(@user)}= @user.name
  %li.breadcrumb-item.active Edit

.row
  .col-sm-10.offset-sm-1.col-md-8.offset-md-2.col-lg-6.offset-lg-3
    = render 'form', action: 'edit', modal: false

app/views/users/index.html.haml
- content_for :title, "Users"
- content_for :heading, 'Users'
- content_for :breadcrumbs do
  %li.breadcrumb-item.active
    = fa_icon 'group'
    Users

-# New User
.btn-group.mb-1{role: 'group'}
  %button.btn.btn-secondary{data: {toggle: 'modal', target: "##{dom_id @user, 'new-modal'}"}, type: 'button'}
    = fa_icon 'plus'
    New User
= render 'modal_form', action: 'new', modal: true

.table-responsive
  %table#users.table
    %thead
      %tr
        %th Name
        %th Email
        %th Roles
        %th Status
    %tbody
      - for user in @users
        %tr
          %td
            - if policy(user).show?
              %a{href: user_path(user)}= user.name
            - else
              = user.name
            - if policy(user).update?
              %small
                %a{href: edit_user_path(user)} Edit
          %td= mail_to(user.email)
          %td
            - if user.roles.empty?
              %span.text-muted None
            - else
              - for role in user.roles
                %span.tag.tag-default.cursor-help{title: role.description}= role.name

          %td
            - if user.disabled_at.nil?
              %span.tag.tag-default.cursor-help Enabled
            - else
              %span.tag.tag-default.cursor-help Disabled

app/views/users/new.html.haml
- content_for :title, 'New User'
- content_for :heading, 'New User'
- content_for :breadcrumbs do
  %li.breadcrumb-item
    %a{href: users_path}= fa_icon 'group', text: 'Users'
  %li.breadcrumb-item.active New User

= render 'form', action: 'new', modal: false

app/views/users/show.html.haml
- content_for :title, "#{@user.name} Details"
- content_for :heading, @user.name
- content_for :subheading, 'Details'
- content_for :breadcrumbs do
  %li.breadcrumb-item
    %a{href: users_path}= fa_icon 'group', text: 'Users'
  %li.breadcrumb-item.active= @user.name

.row
  .col-sm-10.offset-sm-1.col-md-8.offset-md-2.col-lg-6.offset-lg-3
    .card
      .card-block
        %h4.card-title
          = @user.name
          - if policy(@user).edit?
            %small
              %a{href: edit_user_path(@user), data: {target: "##{dom_id @user, 'edit-modal'}", toggle: 'modal'}} Edit
        %dl.mb-0
          %dt Email
          %dd= @user.email
          %dt Last activity
          %dd
            - if @user.last_activity_at
              #{nice_date_time @user.last_activity_at, include_time: true} (#{time_ago_in_words @user.last_activity_at} ago)
            - else
              %span.text-muted Never
          %dt Last login
          %dd
            - if @user.last_login_at
              #{nice_date_time @user.last_login_at, include_time: true} (#{time_ago_in_words @user.last_login_at} ago)
            - else
              %span.text-muted Never
          %dt Last logout
          %dd
            - if @user.last_logout_at
              #{nice_date_time @user.last_logout_at, include_time: true} (#{time_ago_in_words @user.last_logout_at} ago)
            - else
              %span.text-muted Never

        - if @user.disabled_at.nil?
          %hr
          %dl.mb-0
            %dt
              Roles
              - if policy(Contexts::UserRole.new(@user)).edit?
                %a{href: edit_user_roles_path(@user), class: 'font-weight-normal'}
                  = @user.roles.empty? ? 'Add' : 'Edit'
            %dd
              - if @user.roles.empty?
                %span.text-muted No roles assigned
              - else
                - for role in @user.roles
                  %span.tag.tag-default.cursor-help{title: role.description}= role.name
        %hr
        %dl.mb-0
          %dt
            User Status
            %a#disable-button-id{href: 'javascript:void(0);', class: 'font-weight-normal'}
              = 'Edit'
          %dd
            - if @user.disabled_at.nil?
              %span.tag.tag-default.cursor-help Enabled
            - else
              %span.tag.tag-default.cursor-help Disabled
              %br
              %strong Disable Reason:
              %a{class: 'font-weight-normal', style: 'word-wrap: break-word;'}
                = @user.disabled_reason

          %div#disable-form-id(style="display: none;")
            = simple_form_for @user, url: disable_user_path(@user) do |f|
              - if !@user.disabled_at.nil?
                = f.check_box :disabled_at, as: :boolean, id: 'disable-checkbox'
                = f.label :disabled_at, 'Enable'
                %br
              - else
                = f.check_box :disabled_at, as: :boolean, id: 'disable-checkbox'
                = f.label :disabled_at, 'Disable'
                = f.input :disabled_reason, label: 'Reason', wrapper_html: { class: 'required-field' }, input_html: { placeholder: 'Enter a reason', value: ''}
              %p#reason-error.text-danger Reason cannot be blank
              %button.btn.btn-primary#save-button-id{type: 'submit', data: {disable_with: 'Saving...'}}= fa_icon 'check', text: 'Save'
              %button.btn.btn-secondary#cancel-button-id{type: 'button'} Cancel

- if policy(@user).edit?
  = render 'modal_form', action: 'edit', modal: true

:coffeescript
  document.addEventListener 'DOMContentLoaded', ->
  disableButton = document.getElementById('disable-button-id')
  disableForm = document.getElementById('disable-form-id')
  cancelButton = document.getElementById('cancel-button-id')

  if disableButton and disableForm
    disableButton.addEventListener 'click', ->
      disableForm.style.display = 'block'
    cancelButton.addEventListener 'click', ->
      disableForm.style.display = 'none'


    # code for enable/disable save button
    $(document).ready ->
      initialCheckboxState = $('#disable-checkbox').prop('checked')
      $('#save-button-id').prop('disabled', true)
      $('#disable-checkbox').on 'change', ->
        currentCheckboxState = $(this).prop('checked')
        if currentCheckboxState != initialCheckboxState
          $('#save-button-id').prop('disabled', false)
        else
          $('#save-button-id').prop('disabled', true)

      # Use to show blank error reason message
      $('#reason-error').hide()
      $('#save-button-id').on 'click', (event) ->
        reasonInput = $('#user_disabled_reason')
        if reasonInput.val().trim() is ''
          event.preventDefault()
          $('#reason-error').show()
      $('#cancel-button-id').on 'click', ->
        $('#reason-error').hide()

%style
  :plain
    .required-field label::after {
      content: " *";
      color: red;
    }