config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: redirect('/orders')

  get    'login',  to: 'sessions#new', as: 'login'
  post   'login',  to: 'sessions#create'
  get    'logout', to: 'sessions#destroy', as: 'logout'
  delete 'logout', to: 'sessions#destroy'

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :orders, only: :create
    end
    namespace :v2 do
      resources :orders, only: :create
    end
    namespace :v3 do
      resources :orders, only: :create
    end
    namespace :v4 do
      resources :orders, only: :create
    end
  end

  scope :autocomplete, as: :autocomplete do
    get :customers, to: 'autocomplete#customers'
    get :drives, to: 'autocomplete#drives'
  end

  resources :csv_files, path: 'csv', only: %i[create index show]

  get 'help', to: 'help#index', as: 'helps'
  get 'help/*page', to: 'help#show', as: 'help'

  resources :orders, except: [:destroy] do
    collection do
      get 'mine', as: 'my'
    end
    resource :day_count, defaults: { format: 'json' }, only: :show
    resource :state, only: :create
    resources :users, only: %i[create destroy]
  end

  resources :passwords, except: :delete

  resources :reports do
    collection do
      post :preview
    end

    member do
      get :run
    end
  end

  resources :users, except: :destroy do
    resource :roles, only: %i[edit update]
    member do
      patch :disable
    end
  end
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :order_type
  has_many :order_states, dependent: :restrict_with_exception
  has_many :orders, dependent: :restrict_with_exception,
                    inverse_of: :states,
                    through: :order_states

  validates :active, inclusion: { in: [true, false] }
  validates :is_drive_event, inclusion: { in: [true, false] }
  validates :key,
            allow_blank: true,
            length: { maximum: 255 },
            uniqueness: true,
            format: { with: /\A[a-z0-9_]{3,}\Z/,
                      message: 'must be at least 3 lowercase alphanumeric characters (or "_")' }
  validates :label,
            presence: true,
            length: { maximum: 255 }
  validates :notify_by_default, inclusion: { in: [true, false] }
  validates :order_type, presence: true
  validates :percentage,
            presence: true,
            numericality: { greater_than_or_equal_to: 0,
                            less_than_or_equal_to: 100,
                            only_integer: true }
  validates :public_by_default, inclusion: { in: [true, false] }
  validates :is_out_of_our_hands, inclusion: { in: [true, false] }
  validates :leaves_us, inclusion: { in: [true, false] }

  # initial state mappings: order_type.key => state.key
  INITIAL_STATES = {
    'idrive_upload' => 'upload_order_created',
    'idrive_restore' => 'restore_order_created',
    'idrive_one' => 'idrive_one_order_created',
    'idrive_bmr' => 'idrive_bmr_order_created',
    'idrive_bmr_upload' => 'idrive_bmr_upload_order_created',
    'idrive_bmr_restore' => 'idrive_bmr_restore_order_created',
    'idrive360_upload' => 'idrive360_upload_order_created',
    'idrive360_restore' => 'idrive360_restore_order_created',
    'ibackup_upload' => 'ibackup_upload_order_created',
    'ibackup_restore' => 'ibackup_restore_order_created'
  }.freeze
  # states that indicate an order has successfully ended
  SUCCESSFUL_ENDINGS = %w[
    upload_order_completed
    restore_order_completed
    idrive_one_order_shipped
    idrive_bmr_order_shipped
    idrive_bmr_upload_order_completed
    idrive_bmr_restore_order_completed
    idrive360_upload_order_completed
    idrive360_restore_order_completed
    ibackup_upload_order_completed
    ibackup_restore_order_completed
  ].freeze

  # scopes
  scope :usable, ->(order_type) { where(order_type: order_type, active: true).by_percentage }
  scope :by_percentage, -> { order(percentage: :asc) }

  # given a certain express order, get the first state that occurs in the
  # process
  def self.get_initial_state(order_type)
    find_by key: INITIAL_STATES.fetch(order_type.key)
  end

  after_initialize do
    self.active = true if new_record? && active != false
  end

  # does the state successfully complete an order
  def completes_successfully?
    SUCCESSFUL_ENDINGS.include?(key)
  end

  def key=(key)
    super(key.try(:downcase))
  end

  def label_and_percentage
    "#{label} - #{percentage}%#{percentage == 100 ? ' (Completes order)' : ''}"
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :find_order

  # POST /orders/:order_id/state
  # this is for the form at the bottom of the order page where a User can create an OrderState (not a State)
  # This triggers many possible callbacks:
  # Customer notification and IDrive API updating,
  # order completion, drive event creation, and auto-adding user to watchlist
  def create
    @order_state = @order.order_states.build order_state_params
    @order_state.user = User.find(current_user.id)
    if @order_state.save
      flash[:error] = @order_state.errors.full_messages.to_sentence if @order_state.errors.present?
      redirect_to @order, notice: 'Order state added successfully'
    else
      flash.now[:error] = "Error updating order: #{@order_state.errors.full_messages.to_sentence}"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def find_order
    @order = Order.find(params[:order_id])
    authorize @order, :update?
  end

  def order_state_params
    params.require(:order_state).permit(:comments, :did_notify, :is_public, :state_id, :notify_user_id)
  end
end

app/views/states/_form.html.haml
.row
  .col-sm-10.offset-sm-1.col-md-8.offset-md-2
    = simple_form_for @order_state, url: order_state_path(@order), html: {class: 'card'} do |f|
      .card-header
        %strong Update order
      .card-block
        - states = State.usable(@order.order_type)
        - states_data = {}
        - states.map{|s| states_data[s.id] = {notify: s.notify_by_default, public: s.public_by_default, description: s.description}}
        = f.association :state, collection: states, label: 'What happened?', prompt: 'Choose an event...', label_method: :label_and_percentage, input_html: {data: {states: states_data}}
        .row.form-group
          .col-sm-6
            .form-check
              %label.form-check-label.cursor-help{title: 'If checked, the customer will receive an update email with the comments below'}
                = f.check_box :did_notify, {class: 'form-check-input'}
                Notify customer?
          .col-sm-6
            .form-check
              %label.form-check-label.cursor-help{title: "If checked, the #{@order.order_type.product.name} website will be updated with the comments below"}
                = f.check_box :is_public, {class: 'form-check-input'}
                Update #{@order.order_type.product.name} website?
          .col-xs-12
            %small.form-text Want to leave a private/internal comment? Just uncheck the boxes above and your comments will only be visible internally by users of the site.
        = f.input :comments,
                  input_html: {data: {autogrow: true}},
                  hint: "Visible to the customer if \"Notify customer?\" or \"Update #{@order.order_type.product.name} website?\" is checked"
        = f.input :notify_user_id, collection: User.all_by_name(current_user), label: 'Send an email alert to:', wrapper_html: { class: 'm-a-0' }, hint: 'Optional. If chosen, the selected user will receive an email notification with any comments you write.'
      .card-footer
        %button.btn.btn-primary{type: 'submit', data: {disable_with: 'Saving Order State...'}} Update

app/views/states/_list.html.haml
.card.mb-2
  .card-header
    %b
      = "Order Updates (#{@order_states.size})"
  %ul.list-group.list-group-flush
    - if @order_states.empty?
      %li.list-group-item.text-xs-center
        No activity here...

    - else
      - for order_state in @order_states
        %li.list-group-item
          .row
            .col-md-8.col-xl-7
              %h6.order-state-header
                %strong= order_state.state.label
                %span.text-muted
                  on
                  = render 'dates/friendly_date', date_time: order_state.created_at
                  - update_sep = order_state.updated_at > order_state.created_at ? ', ' : ''
                  = "#{order_state.user.present? ? "by #{order_state.user.name}" : ''}#{update_sep}"
                  - if update_sep.present?
                    updated
                    = render 'dates/friendly_date', date_time: order_state.updated_at
                  - if order_state.private?
                    %span.tag.tag-default{title: 'This update is only visible internally on this site'} Private note
              %p.text-plain.order-state-comments= auto_link_to_ticketing(order_state.comments)
            .col-md-4.col-lg-3.offset-lg-1.offset-xl-2
              %ul.list-unstyled
                %li
                  = fa_icon boolean_icon(order_state.did_notify?), class: 'fa-fw'
                  Customer
                  = order_state.did_notify? ? '' : 'not'
                  notified
                %li
                  = fa_icon boolean_icon(order_state.is_public?), class: 'fa-fw'
                  IDrive
                  = order_state.is_public? ? '' : 'not'
                  updated

- if policy(@order).update?
  = render 'states/form'

app/views/states/new.html.haml
- content_for :title, "New State for Order ##{@order.id}"
- content_for :heading, "New Order ##{@order.id} State"
- content_for :breadcrumbs do
  %li.breadcrumb-item
    %a{href: orders_path} Orders
  %li.breadcrumb-item
    %a{href: order_path(@order)} Order ##{@order.id}
  %li.breadcrumb-item
    %a{href: order_path(@order)+'#new_order_state'} States
  %li.breadcrumb-item.active New

= render 'form'