config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: redirect('/orders')

  get    'login',  to: 'sessions#new', as: 'login'
  post   'login',  to: 'sessions#create'
  get    'logout', to: 'sessions#destroy', as: 'logout'
  delete 'logout', to: 'sessions#destroy'

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :orders, only: :create
    end
    namespace :v2 do
      resources :orders, only: :create
    end
    namespace :v3 do
      resources :orders, only: :create
    end
    namespace :v4 do
      resources :orders, only: :create
    end
  end

  scope :autocomplete, as: :autocomplete do
    get :customers, to: 'autocomplete#customers'
    get :drives, to: 'autocomplete#drives'
  end

  resources :csv_files, path: 'csv', only: %i[create index show]

  get 'help', to: 'help#index', as: 'helps'
  get 'help/*page', to: 'help#show', as: 'help'

  resources :orders, except: [:destroy] do
    collection do
      get 'mine', as: 'my'
    end
    resource :day_count, defaults: { format: 'json' }, only: :show
    resource :state, only: :create
    resources :users, only: %i[create destroy]
  end

  resources :passwords, except: :delete

  resources :reports do
    collection do
      post :preview
    end

    member do
      get :run
    end
  end

  resources :users, except: :destroy do
    resource :roles, only: %i[edit update]
    member do
      patch :disable
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users

  # validation
  validates :key,
            presence: true,
            length: { maximum: 255 },
            format: {
              with: /\A[a-z0-9_]{3,}\Z/,
              message: 'must be at least 3 lowercase alphanumeric characters (or "_")'
            },
            uniqueness: true
  validates :name, presence: true, length: { maximum: 255 }
  validates :description, presence: true, length: { maximum: 255 }

  # scopes
  scope :by_name, -> { order(name: :asc) }
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :find_user
  before_action :setup_view

  # GET /users/:user_id/roles/edit
  def edit
    authorize Contexts::UserRole.new(@user)
    @chosen_roles = @user.roles.by_name
  end

  # PATCH/PUT /users/:user_id/roles
  def update
    roles = Role.where(id: role_params[:roles])
    user_roles = Contexts::UserRole.new(@user, roles)
    authorize user_roles

    begin
      @user.roles = user_roles.roles
      flash[:notice] = 'Roles updated successfully'
      redirect_to user_path(user_roles.user)
    rescue ActiveRecord::RecordNotSaved
      @chosen_roles = user_roles.roles
      flash[:error] = 'Role update failed'
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end

  def role_params
    params.require(:user).permit(roles: [])
  end

  def setup_view
    @roles = Role.by_name
  end
end

app/views/roles/edit.html.haml
- content_for :title, "Editing roles for #{@user.name}"
- content_for :breadcrumbs do
  %li.breadcrumb-item
    %a{href: users_path}= fa_icon 'group', text: 'Users'
  %li.breadcrumb-item
    %a{href: user_path(@user)}= @user.name
  %li.breadcrumb-item.active Edit Roles

.row
  .col-sm-10.offset-sm-1.col-md-8.offset-md-2.col-lg-6.offset-lg-3
    = simple_form_for @user, url: user_roles_path(@user), html: {class: 'card'} do |f|
      .card-header
        %b= yield :title
      .card-block
        = f.label :roles
        = hidden_field_tag 'user[roles][]', nil, id: :user_roles
        - for role in @roles
          .form-check
            %label.form-check-label
              = check_box_tag 'user[roles][]', role.id, @chosen_roles.collect(&:id).include?(role.id), id: "user_roles_#{role.id}", class: 'form-check-input'
              = "#{role.name} - #{role.description}"
      .card-footer
        %button.btn.btn-primary{type: 'submit', data: {disable_with: 'Saving...'}} Save